"""メールの件名と本文の組み立て。AWS に依存しない純粋関数のみ。

SNS の Subject は ASCII のみ・100文字未満という制約があるため、件名は英語で組み立てる。
Message（本文）には制約がないので日本語で記述する。
"""

import unicodedata
from decimal import ROUND_HALF_UP, Decimal

from .cost_explorer import MonthlyCost
from .periods import ReportPeriod

DEFAULT_TOP_N = 10
_NAME_WIDTH = 28
_AMOUNT_WIDTH = 9
_RANK_PREFIX_WIDTH = 5  # " NN. " の表示幅
_CENT = Decimal("0.01")
_TENTH = Decimal("0.1")
_SEPARATOR = "=" * 44
_FOOTER = "--\nGenerated by aws-monthly-cost-report"


def visual_width(text: str) -> int:
    """等幅フォントでの表示幅。全角文字を2桁として数える。"""
    return sum(2 if unicodedata.east_asian_width(char) in ("W", "F") else 1 for char in text)


def _pad(text: str, width: int) -> str:
    """表示幅を基準に右側を空白で埋める。"""
    return text + " " * max(width - visual_width(text), 0)


def _amount(value: Decimal) -> str:
    return "{:.2f}".format(value.quantize(_CENT, rounding=ROUND_HALF_UP))


def _signed_amount(value: Decimal) -> str:
    rounded = value.quantize(_CENT, rounding=ROUND_HALF_UP)
    sign = "+" if rounded >= 0 else "-"
    return "{}{:.2f}".format(sign, abs(rounded))


def _percentage(current: Decimal, previous: Decimal):
    """変化率。前月が 0 のときは計算できないので None を返す。"""
    if previous == 0:
        return None
    rounded = ((current - previous) / previous * 100).quantize(_TENTH, rounding=ROUND_HALF_UP)
    sign = "+" if rounded >= 0 else "-"
    return "{}{:.1f}%".format(sign, abs(rounded))


def build_subject(period: ReportPeriod, target: MonthlyCost, previous: MonthlyCost) -> str:
    """ASCII のみの件名を返す。"""
    parts = [
        "[AWS Cost]",
        period.target_label,
        "total",
        _amount(target.total),
        target.unit,
    ]
    percentage = _percentage(target.total, previous.total)
    if percentage is not None:
        parts.append("({})".format(percentage))
    return " ".join(parts)


def build_error_subject() -> str:
    """ASCII のみのエラー件名を返す。"""
    return "[AWS Cost][ERROR] monthly cost report failed"


def _service_lines(target: MonthlyCost, previous: MonthlyCost, top_n: int):
    if not target.by_service:
        return ["  対象期間のコストデータがありません。"]

    ranked = sorted(target.by_service.items(), key=lambda item: item[1], reverse=True)
    lines = []

    for rank, (service, amount) in enumerate(ranked[:top_n], start=1):
        delta = amount - previous.by_service.get(service, Decimal(0))
        lines.append(
            " {:>2}. {} {:>{width}} {}  ({})".format(
                rank,
                _pad(service, _NAME_WIDTH),
                _amount(amount),
                target.unit,
                _signed_amount(delta),
                width=_AMOUNT_WIDTH,
            )
        )

    remainder = ranked[top_n:]
    if remainder:
        subtotal = sum((amount for _, amount in remainder), Decimal(0))
        label = "その他 ({}件)".format(len(remainder))
        lines.append(
            "{}{} {:>{width}} {}".format(
                " " * _RANK_PREFIX_WIDTH,
                _pad(label, _NAME_WIDTH),
                _amount(subtotal),
                target.unit,
                width=_AMOUNT_WIDTH,
            )
        )

    return lines


def build_body(
    period: ReportPeriod,
    target: MonthlyCost,
    previous: MonthlyCost,
    account_id: str,
    top_n: int = DEFAULT_TOP_N,
) -> str:
    """レポート本文（日本語プレーンテキスト）を組み立てる。"""
    percentage = _percentage(target.total, previous.total)
    delta_suffix = (
        "({})".format(percentage) if percentage is not None else "(前月 0.00 のため率は非表示)"
    )

    lines = [
        _SEPARATOR,
        " AWS 月次コストレポート",
        _SEPARATOR,
        "アカウント : {}".format(account_id),
        "対象期間   : {} 〜 {}".format(period.target_start.isoformat(), period.target_end.isoformat()),
        "",
        "■ 合計",
        "  当月    : {} {}".format(_amount(target.total), target.unit),
        "  前月    : {} {}".format(_amount(previous.total), previous.unit),
        "  差分    : {} {} {}".format(
            _signed_amount(target.total - previous.total), target.unit, delta_suffix
        ),
        "",
        "■ サービス別内訳 (上位{}件 / UnblendedCost)".format(top_n),
    ]
    lines.extend(_service_lines(target, previous, top_n))
    lines.extend(["", _FOOTER])

    return "\n".join(lines)


def build_error_body(period: ReportPeriod, error: BaseException, request_id: str) -> str:
    """エラー通知の本文（日本語プレーンテキスト）を組み立てる。

    スタックトレースはメールに載せず CloudWatch Logs に残す。
    """
    lines = [
        _SEPARATOR,
        " AWS 月次コストレポート / エラー",
        _SEPARATOR,
        "月次コストレポートの生成に失敗しました。",
        "",
        "対象期間     : {} 〜 {}".format(
            period.target_start.isoformat(), period.target_end.isoformat()
        ),
        "エラー種別   : {}".format(type(error).__name__),
        "エラー内容   : {}".format(error),
        "リクエストID : {}".format(request_id),
        "",
        "詳細は CloudWatch Logs を確認してください。",
        "",
        _FOOTER,
    ]
    return "\n".join(lines)
